version: '3'
services:
  seamless-demo-notification:
    build: ../seamless-demo-notification
    image: 697645747316.dkr.ecr.us-east-1.amazonaws.com/seamless-cicd/seamless-demo-notification:0c35e04a7206bb0db0edcfd8fee1fe481b4229b1
    environment:
      - NOTIFICATION_ENDPOINT=https://eo181huqgm366vz.m.pipedream.net

  seamless-demo-payment:
    build: ../seamless-demo-payment
    # Image will be overwritten with new image built from source code
    image: seamless-demo-payment:latest
    depends_on:
      - seamless-demo-notification

  seamless-demo-integration-test:
    build: .
    # Image will be overwritten with new image built from source code
    image: seamless-demo-payment-integration-test:latest
    depends_on:
      - seamless-demo-payment
      - seamless-demo-notification
